[ENH] interfacing Poission regressors from sklearn
sktime/skpro pull request #213
Opened 2024-03-14 19:12 UTC by nilesh05apr

#### Reference Issues/PRs
https://github.com/sktime/skpro/issues/7

#### What does this implement/fix? Explain your changes.
Added interface for Poisson Regressor

#### Does your contribution introduce a new dependency? If yes, which one?
None

#### Did you add any tests for the change?
None

#### PR checklist

##### For all contributions
- [x] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-03-14 19:15 UTC, nilesh05apr commented
@fkiraly can you please approve changes? I will keep adding more linear models.

2024-03-15 18:40 UTC, fkiraly requested changes
Thanks, nice idea!

However, I think more is needed to add the poisson regressor.

The current `SklearnProbaReg` assumes a normal distribution, and `predict` having an `return_std` argument. This is not true for the sklearn `PoissonRegressor`:

* the assumed return distribution is the Poisson distribution
* `predict` does not have a `return_std`, it simply returns the rate parameter.

To make this work, you would have to:

* add a tabular Poisson distribution to the `distributions` module
* use that to encode the output of `predict

2024-03-16 09:31 UTC, nilesh05apr commented
@fkiraly thanks for the review, I will implement the changes soon

2024-04-25 23:33 UTC, fkiraly approved these changes
Abandoned - wrapped it up so it can be merged

2024-04-25 23:46 UTC, merged