[ENH] Chi-Squared Distribution #22
sktime/skpro pull request #217
Opened 2024-03-23 18:59 UTC by sukjingitsit

#### Reference Issues/PRs

Addresses #22 for chi-squared case

#### What does this implement/fix? Explain your changes.

Implements some methods for chi-squared distribution
#### Does your contribution introduce a new dependency? If yes, which one?
No

#### What should a reviewer concentrate their feedback on?

Current state of code, and what all capabilities need to be modified / made better (particularly, I am trying to implement energy and make ppf more native than a scipy wrapper)
#### Did you add any tests for the change?
Nope

#### Any other comments?

#### PR checklist

##### For all contributions
- [ No] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [Yes ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

Thanks for contributing!
-->

2024-03-23 20:18 UTC, fkiraly requested changes
Nice contribution!

Code formatting checks are failing, see here for a guide how to set this up locally:
https://www.sktime.net/en/stable/developer_guide/coding_standards.html

For the energy, let me know if you need help. Does the reference from the issue not have an explicit formula?

2024-03-23 22:04 UTC, sukjingitsit commented
I do not understand what the build issue is, as it doesn't seem to show the files I modified, rather some other files

2024-03-24 00:36 UTC, fkiraly commented
note sure, I've restarted the tests - let's see.

2024-03-24 01:17 UTC, fkiraly commented
failures seem genuine - methods return unexpected values. Have you run `check_estimator` on the distribution?

2024-04-25 22:51 UTC, merged