Lognormal probability distribution
sktime/skpro pull request #218
Opened 2024-03-24 06:02 UTC by bhavikar04

#### Reference Issues/PRs
#22 

#### What does this implement/fix? Explain your changes.
Lognormal probability distribution

#### Does your contribution introduce a new dependency? If yes, which one?
no

#### What should a reviewer concentrate their feedback on?

#### Did you add any tests for the change?
no

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ x] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-04-07 11:45 UTC, fkiraly commented
do you need feedback on this?
I left some comments on the old version: https://github.com/sktime/skpro/pull/214

FYI, you do not need to close PR to update them, if you update the branch on your fork, the PR will automatically update.

2024-04-09 19:07 UTC, bhavikar04 commented
> do you need feedback on this? I left some comments on the old version: #214
> 
> FYI, you do not need to close PR to update them, if you update the branch on your fork, the PR will automatically update.

the energy functional hasn't been worked out

2024-04-11 19:52 UTC, fkiraly requested changes
Thanks!

Looks ok. Can you quickly explain how you arrived at the energy term?

Also, please make sure to format your code properly, or the tests will not run:
https://www.sktime.net/en/stable/developer_guide/coding_standards.html

2024-04-18 08:07 UTC, fkiraly approved these changes
Since you did not comment, I assume you are no longer working on this, so I've wrapped this up now for merge

2024-04-18 08:08 UTC, merged