[ENH] Logistic distribution
sktime/skpro pull request #241
Opened 2024-04-06 18:45 UTC by malikrafsan

#### Reference Issues/PRs

https://github.com/sktime/skpro/issues/22

#### What does this implement/fix? Explain your changes.

Logistic probability distribution

#### Does your contribution introduce a new dependency? If yes, which one?

no

#### What should a reviewer concentrate their feedback on?

- [ ] Energy formula for logistic distribution

#### Did you add any tests for the change?

- Yes, I try to install this library locally using `pip install --editable .[dev,test]` and create simple driver program to use this new distribution

#### Any other comments?

* I use the formula from Wikipedia, which can be accessed [here](https://en.wikipedia.org/wiki/Logistic_distribution)
* For log_pdf, I use wolfram alpha to derive the formula, here is the screenshot
![Screenshot from 2024-04-07 01-05-52](https://github.com/sktime/skpro/assets/77711133/03f5b10d-956d-492f-8125-2d17f43f77cc)

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-04-06 21:13 UTC, fkiraly commented
> For `log_pdf`, I use wolfram alpha to derive the formula

Interesting - I would just have used the standard logarithm rules to cancel exps etc.

Do you have an opinion on which representation is more stable, numerically?

Intuitively, at least, I would think cancelling as many exps as possible is better.

2024-04-06 21:14 UTC, fkiraly commented
PS: no need to close PR and reopen, if you update your branch on your fork, the PR automatically gets updated.

2024-04-07 06:01 UTC, malikrafsan commented
> PS: no need to close PR and reopen, if you update your branch on your fork, the PR automatically gets updated.

Previously, I incorrectly named the branch, it should be logistic, but I named the branch as weibull, sorry about that 😅😅

2024-04-07 06:28 UTC, malikrafsan commented
> Interesting - I would just have used the standard logarithm rules to cancel exps etc.

Thank you so much on your thoughts about this! Based on my manual calculation it should be 

$(-\frac{x-\mu}{s}) - ln(s) - 2ln(1+e^{-\frac{x-\mu}{s}})$

> Do you have an opinion on which representation is more stable, numerically?

I'm uncertain myself about which representation is numerically more stable 😅😅

Previously I leaned towards the result from Wolfram Alpha as it offered a relatively simpler equation, but I am also not really sure whether it is the best solution

After some careful consideration, I think using the standard logarithm rule would be more intuitive to use and to be read. I will change it accordingly 😅😅

2024-04-07 09:39 UTC, fkiraly commented
> Thank you so much on your thoughts about this! Based on my manual calculation it should be

Looks correct to me. I'd use `numpy` `logaddexp` (or the `scipy` distribution directly)

2024-04-07 22:42 UTC, fkiraly requested changes
Thanks!

* could you kindly add the distribution to the api reference in `docs`?
* not blocking, but could you kindly look at the comment re logs and cancellation?

2024-04-09 16:24 UTC, malikrafsan commented
> I'd use numpy logaddexp 
Sure, I have adjusted the code to use the function

> could you kindly add the distribution to the api reference in docs?
Sure, I have added the new class to the API reference

> not blocking, but could you kindly look at the comment re logs and cancellation?
I am not sure I understand this, what does comment re logs and cancellation mean? Thank you!

Please let me know if there is any concern or feedback, thank you so much!

2024-04-10 11:36 UTC, fkiraly commented
> Interesting - I would just have used the standard logarithm rules to cancel exps etc.

The above is what I meant, yes

2024-04-18 08:03 UTC, fkiraly approved these changes
I'm assuming you're no longer working on this, so I'm wrapping this up now.

2024-04-18 09:39 UTC, merged

2024-04-28 17:25 UTC, malikrafsan commented
> I'm assuming you're no longer working on this, so I'm wrapping this up now.

Hi @fkiraly,  I very much apologize for the delay in completing the PR without notifying you further. Thank you so much for wrapping this PR up. Please kindly let me know if there's anything I can assist with or if there are any adjustments needed 🙏🙏

2024-04-29 08:54 UTC, fkiraly commented
no worries - a message would have been helpful, but it is not unusual that PRs do not get completed, and we wrap those up that are close to the finish line.

Thanks for your contibutions with the scipy adapter, these are really nice!