[ENH] Add Adapter for Scipy Distributions
sktime/skpro pull request #287
Opened 2024-04-29 07:16 UTC by malikrafsan

#### Reference Issues/PRs

Fixes #227 

#### What does this implement/fix? Explain your changes.

- Adapter for Scipy distributions
- Fisk Distribution using Scipy Adapter

#### Does your contribution introduce a new dependency? If yes, which one?

no

#### What should a reviewer concentrate their feedback on?

- [ ] Adapter structure

#### Did you add any tests for the change?

- I try to install this library locally using `pip install --editable .[dev,test]` and create a simple driver program to use this new distribution
- I try to compare several methods of the existing Fisk distribution with proposed one and they produce the same result 

#### Any other comments?

#### PR checklist

##### For all contributions
- [ ] I've added myself to the [list of contributors](https://github.com/sktime/skpro/blob/main/CONTRIBUTORS.md) with any new badges I've earned :-)
  How to: add yourself to the [all-contributors file](https://github.com/sktime/skpro/blob/main/.all-contributorsrc) in the `skpro` root directory (not the `CONTRIBUTORS.md`). Common badges: `code` - fixing a bug, or adding code logic. `doc` - writing or improving documentation or docstrings. `bug` - reporting or diagnosing a bug (get this plus `code` if you also fixed the bug in the PR).`maintenance` - CI, test framework, release.
  See here for [full badge reference](https://allcontributors.org/docs/en/emoji-key)
- [ ] The PR title starts with either [ENH], [MNT], [DOC], or [BUG]. [BUG] - bugfix, [MNT] - CI, test framework, [ENH] - adding or improving code, [DOC] - writing or improving documentation or docstrings.

##### For new estimators
- [ ] I've added the estimator to the API reference - in `docs/source/api_reference/taskname.rst`, follow the pattern.
- [ ] I've added one or more illustrative usage examples to the docstring, in a pydocstyle compliant `Examples` section.
- [ ] If the estimator relies on a soft dependency, I've set the `python_dependencies` tag and ensured
  dependency isolation, see the [estimator dependencies guide](https://www.sktime.net/en/latest/developer_guide/dependencies.html#adding-a-soft-dependency).

2024-04-29 08:50 UTC, fkiraly requested changes
Thanks!

This was extremely quick and exactly what I meant! Really nice!

Some comments:

* good idea to have separate discrete/continuous. Currently, the interface indeed is different. There is also the issue of not having pmf in the base class.
    * for the time being, I think we can leave the handling of `pmf` and `log_pmf` as you suggest. However, you have certainly noted the missing handling of `pmf` in the base class, and that's why you tried to work around it wiht the second class. I would recommend, could you open an issue on implementing the `pmf` in the base class? Not necessarily sth to work on right now, but to keep track of what we still need to do. You could also pick it up later in a separate PR, if you'd like.
* what I would do is *replace entirely* the current `Fisk` and `Poisson` distribution implementations with the scipy based one. There is no difference in the logic, only the code is more streamlined through the adapter.
    * don't worry about delete/replace, the classes were written expressly with the idea in mind to later refactor them to a single adapter. What is important to check that this does not change anything, so is a proper refactor - see below.
* what could be helpful is to add some tests for the adapter class, e.g., take `Fisk` and check its outputs against direct outputs from `scipy`. That way we test that the adapter class is really adapting 1:1, and we can check that "before and after" are the same, for this refactor.
* finally, may I suggest to pick one more distribution from `scipy` and add it as an `skpro` object? How about a beta distribution, given that it is on the priority list in #22?
    * with the adapter, it should now be easy to add dozens of distributions with minimal work overhead, by using `scipy`. I would leave this to separate PR. And of course the more exotic properties like energy will not be provided by `scipy`.

2024-05-01 09:30 UTC, malikrafsan commented
> I would recommend, could you open an issue on implementing the pmf in the base class? 

Sure! I would love to do it

2024-05-01 09:56 UTC, malikrafsan commented
> don't worry about delete/replace, the classes were written expressly with the idea in mind to later refactor them to a single adapter.

Ahh I see, previously, I was a bit afraid to delete them 😅 Okay, I will replace them!

2024-05-01 10:37 UTC, malikrafsan commented
> what could be helpful is to add some tests for the adapter class, e.g., take Fisk and check its outputs against direct outputs from scipy. That way we test that the adapter class is really adapting 1:1, and we can check that "before and after" are the same, for this refactor.

I tried to run the test, but it turns out that, after changes, Fisk and Poisson failed the test. I will try to understand the test cases and pytest first as this is also my first time having hands-on on pytest.

Also for confirmation, from what I understand, it is better for me to make new test file to compare the result of the scipy adapter (let's say `Fisk`) vs result directly from scipy right? I will try to make it after fixing the test first 

![Screenshot from 2024-05-01 17-33-02](https://github.com/sktime/skpro/assets/77711133/80d17e05-b29c-4c6f-a740-7e89efae73d7)

2024-05-01 17:43 UTC, fkiraly commented
(I fixed the typo in the `_ppf` arg, hope that is ok)

2024-05-03 08:14 UTC, malikrafsan commented
> (I fixed the typo in the _ppf arg, hope that is ok)
Sure! Absolutely no problem for me! Thank you for fixing it 😄

> All looks good, unfortunately the failures are on 3.8, from type annotations, square brackets are not supported. Would you be so kind to remove these? These are internal annotations anyway, in private methods.
Thank you so much for pointing this out! I have removed the type annotations square brackets and the test work fine after that! 😄

> what could be helpful is to add some tests for the adapter class
I have also added the pytest for scipy adapter class, please let me know if you have any feedback for the test!

2024-05-03 14:59 UTC, fkiraly approved these changes
Thanks - this is great!

In a separate step, we may want to move the "return 0" logic into the `BaseDistribution` class, and base it on the tag `distribution_type`.

2024-05-03 15:00 UTC, fkiraly commented
What would be great is adding a new distibution, to check whether it is indeed easy - how about beta? You can do this in another PR based on this one.

2024-05-03 22:56 UTC, merged

2024-05-04 10:52 UTC, malikrafsan commented
> What would be great is adding a new distribution, to check whether it is indeed easy to use this adapter - how about beta? You can do this in another PR based on this one.

Sure, I would like to do that!